# Site wide configuration

title:            Dreaming
locale:           China
#url:              http://somnusfish.github.io
url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Lu Ma
  avatar: me.jpg
  bio: "You have to kill those excuses, or they will kill you."
  email: somnusfish@gmail.com
  disqus-shortname: 
  twitter: #username
  facebook: somnus Ma
  google:
    plus: somnusfish
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: somnusfish
  stackoverflow: http://stackoverflow.com/users/1856642/lu-ma
  linkedin: Lu Ma
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: somnusfish
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
