# Site wide configuration

title:            Dreaming
locale:           China
url:              http://somnusfish.github.io
#url:              http://localhost:4000


# Site owner
owner:
  name: Lu Ma
  avatar: me.jpg
  bio: "You have to kill those excuses, or they will kill you."
  email: somnusfish@gmail.com
  disqus-shortname: 
  twitter: #username
  facebook: somnusfish
  google:
    plus: somnusfish
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: somnusfish
  stackoverflow: http://stackoverflow.com/users/1856642/lu-ma
  linkedin: Lu Ma
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: somnusfish
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
